version: 2.1
orbs:
  gh: circleci/github-cli@1.0.3
jobs:
    build:
        docker:
            - image: circleci/node:14.17-browsers
        steps:
            - checkout
            - restore_cache:
                  keys:
                      - v1-dependencies-{{ checksum "package.json" }}-{{ checksum "./angular/components/package.json" }}-{{ checksum "./react/icons/package.json" }}
                      - v1-dependencies-
            - run:
                  name: Install Dependencies
                  command: |
                      yarn install
                      cd react/icons
                      yarn install
                      cd ../demo
                      yarn install
                      cd ../../angular/components
                      yarn install
                      cd ../demos/showcase
                      yarn install
                      cd ../../../react-native/icons
                      yarn install
            - save_cache:
                  paths:
                      - node_modules
                      - react/icons/node_modules
                      - angular/components/node_modules
                      - react-native/icons/node_modules
                  key: v1-dependencies-{{ checksum "package.json" }}-{{ checksum "./angular/components/package.json" }}-{{ checksum "./react/icons/package.json" }}
            - run:
                  name: Prettier Check
                  command: |
                      yarn prettier:check
                      cd ..
            - run:
                  name: Lint
                  command: |
                      yarn lint
                      cd ..
            - run:
                  name: Build Packages
                  command: |
                      yarn build:all
            - run:
                  name: Test
                  command: |
                      yarn test:functions
                      cd ..
            - run:
                  name: Build Demos
                  command: |
                      yarn test:demos
                      cd ..
            - persist_to_workspace:
                  root: .
                  paths:
                    - angular/dist
                    - react/icons/dist
                    - react-native/dist

    publish:
      docker:
        - image: circleci/node:14.17-browsers
      steps:
        - checkout
        - attach_workspace:
            at: .
        - run:
            name: Authenticate with registry
            command:  |
              echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/.npmrc
              echo "//registry.yarnpkg.com/:_authToken=$NPM_TOKEN" >> ~/.npmrc
        - run:
            name: Publish @pxblue/ng-progress-icons
            command: cd angular/components && yarn publish:package -b $CIRCLE_BRANCH
        - run:
            name: Publish @pxblue/react-progress-icons
            command: cd react/icons && yarn publish:package -b $CIRCLE_BRANCH
        - run:
            name: Publish @pxblue/react-native-progress-icons
            command: cd react-native && yarn publish:package -b $CIRCLE_BRANCH

    tag:
      docker:
        - image: circleci/node:14.17-browsers
      steps:
        - checkout
        - gh/setup
        - attach_workspace:
            at: .
        - run:
            name: Tag @pxblue/ng-progress-icons
            command: cd angular/components && cp ../CHANGELOG.md CHANGELOG.md && yarn tag:package -b $CIRCLE_BRANCH -s -ng-progress-icons
        - run:
            name: Publish @pxblue/react-progress-icons
            command: cd react/icons && yarn tag:package -b $CIRCLE_BRANCH -s -react-progress-icons
        - run:
            name: Publish @pxblue/react-native-progress-icons
            command: cd react-native/icons && cp ../CHANGELOG.md CHANGELOG.md && yarn tag:package -b $CIRCLE_BRANCH -s -react-native-progress-icons
workflows:
  version: 2
  icons:
    jobs:
      - build
      - publish:
          requires:
            - build
          filters:
            branches:
              only:
                - master
                - dev
